package helper;

public class DataProviderSection {
   /*
    Saction name for Open-Ended with Bank
    */

    public static final String FUTURE_WITH_DWNPAY_OPENENDED_MONTHLY_BANK = "OPENEND MONTHLY WITH DWNPAY BEG DUE DATE FUTURE BY BANK";
    public static final String PAST_WITHOUT_DWNPAY_OPENENDED_MONTHLY_BANK = "OPENEND MONTHLY WITHOUT DWNPAY BEG PAST";
    public static final String CURRENT_WITH_DWNPAY_OPENENDED_MONTHLY = "OPENEND MONTHLY WITH DWNPAY BEG DUE DATE CURRENT";
    public static final String CURRENT_WITHOUT_DWNPAY_OPENENDED_QUARTERLY = "OPENEND QUATERLY BEG CURRENT";
    public static final String CURRENT_WITHOUT_DWNPAY_OPENENDED_ANNUALLY = "OPENEND ANNUALLY WITHOUT DWNPAY BEG CURRENT";
    public static final String PAST_WITHOUT_DWNPAY_OPENENDED_ANNUALLY = "OPENEND ANNUALLY WITHOUT DWNPAY BEG PAST";
    public static final String FUTURE_WITH_DWNPAY_OPENENDED_ANUALLY = "OPENEND ANNUALLY WITH DWNPAY BEG DATE FUTURE";
    public static final String FUTURE_WITHOUT_DWNPAY_OPENENDED_BIWEEKLY = "OPENEND BIWEEKLY WITHOUT DWNPAY BEG FUTURE";
    public static final String CURRENT_WITH_DWNPAY_OPENENDED_BIWEEKLY = "OpenEndedBiWeeklyWithBegDateCurrent";
    public static final String PAST_WITH_DWNPAY_OPENENDED_SEMIANNUALLY_BANK = "OPENEND MONTHLY WITH DWNPAY BEG DUE DATE FUTURE BY BANK";
    public static final String FUTURE_WITHOUT_DWNPAY_OPENENDED_MONTHLY_DUE_DATE_FUTURE_BANK = "OPENEND MONTHLY WITHOUT DWNPAY BEG AND DUE DATE FUTURE";
    public static final String CURRENT_WITHOUT_DWNPAY_OPENENDED_MONTHLY_BANK = "OPEN ENDED MONTHLY WITOUT DOWN PAYMENT WITH BEG DATE CURRENT";
    public static final String CURRENT_WITH_DWNPAY_OPENENDED_MONTHLY_BANK = "OPENEND MONTHLY WITH DWNPAY BEG CURRENT";
    public static final String FUTURE_WITHOUT_DWNPAY_OPENENDED_MONTHLY_BANK = "OPENEND MONTHLY WITHOUT DWNPAY BEG DATE FUTURE";
    public static final String FUTURE_WITH_DWNPAY_OPENENDED_MONTHLY_DUE_DATE_FUTURE_BANK = "OPENEND MONTHLY WITH DWNPAY BEG AND DUE DATE FUTURE";
    public static final String CURRENT_WITH_DWNPAY_OPENENDED_QUARTERLY_BANK = "OPENEND QTR WITH DWNPAY BEG CURRENT";
    public static final String PAST_WITH_DWNPAY_OPENENDED_QUARTERLY_BANK = "OPENEND QUARTERLY WITH DWNPAY BEG PAST";
    public static final String CURRENT_WITH_DWNPAY_OPENENDED_SEMIANNUALLY = "OPENEND SEMIANNUALLY WHEN BEG CURRENT";
    public static final String CURRENT_WITH_DWNPAY_OPENENDED_MONTHLY_DUE_DATE_CURRENT_BANK = "OPENEND MONTHLY WHEN BEG CURRENT";
    public static final String CURRENT_WITH_DWNPAY_OPENENDED_WEEKLY_DUE_DATE_CURRENT_BANK = "OPENEND WEEKLY WHEN BEG CURRENT";
    public static final String PAST_WITH_DWNPAY_OPENENDED_SEMIANNUALLY_DUE_DATE_PAST_BANK = "OPENEND SEMI-ANNUALLY WHEN BEG PAST";
    public static final String PAST_WITH_DWNPAY_OPENENDED_QUARTERLY_DUE_DATE_PAST_BANK = "OPENEND QUARTERLY WHEN BEG PAST";
    public static final String PAST_WITHOUT_DWNPAY_OPENENDED_SEMIANNUALLY = "OPENEND SEMIANNUALLY WITHOUT DWNPAY BEG PAST";
    public static final String FUTURE_WITHOUT_DWNPAY_OPENENDED_SEMIANNUALLY = "OPENEND SEMIANNUALLY WITHOUT DWNPAY BEG FUTURE";
    public static final String PAST_WITH_DWNPAY_OPENENDED_MONTHLY_DUE_DATE_PAST_BANK = "OPENEND MONTHLY WITH DWN WHEN BEG PAST";
    public static final String PAST_WITH_DWNPAY_OPENENDED_BIWEEKLY_DUE_DATE_PAST_BANK = "OPENEND BI-WEEKLY WITH DWN WHEN BEG PAST";
    public static final String PAST_WITH_DWNPAY_OPENENDED_ANNUALLY_DUE_DATE_PAST_BANK = "PAST MULTIPLE SUBS ANNUALLY WITH DWN WHEN BEG PAST";
    public static final String PAST_WITHOUT_DWNPAY_OPENENDED_WEEKLY_BANK = "OPENEND WEEKLY WITHOUT DWNPAY BEG AND Due DATE PAST";
    public static final String CURRENT_WITHOUT_DWNPAY_OPENENDED_WEEKLY_BANK = "OPENEND WEEKLY WITHOUT DWNPAY BEG CURRENT";
    public static final String FUTURE_WITHOUT_DWNPAY_OPENENDED_WEEKLY_BANK = "OPENEND WEEKLY WITHOUT DWNPAY BEG FUTURE";
    /*
    Section name for Open-Ended with card
      */
    public static final String PAST_WITH_DWNPAY_OPENENDED_MONTHLY_CARD = "OPENEND MONTHLY WITH DWNPAY BEG PAST BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_OPENENDED_SEMIANNUALLY_CARD = "OPENEND SEMIANNUALLY WITH DWNPAY BEG PAST BY CARD";
    public static final String PAST_WITH_DWNPAY_OPENENDED_WEEKLY_CARD = "OPENEND WEEKLY WITH DWNPAY BEG PAST BY CARD";
    public static final String FUTURE_WITHOUT_DWNPAY_OPENENDED_WEEKLY_CARD = "OPENEND WEEKLY WHEN BEG FUTURE BY CARD";
    public static final String FUTURE_WITHOUT_DWNPAY_OPENENDED_BIWEEKLY_CARD = "OPENEND BIWEEKLY WHEN BEG FUTURE BY CARD";
    public static final String CURRENT_WITHOUT_DWNPAY_OPENENDED_MONTHLY_CARD = "OPENEND SUB MONTHLY BEG DATE CURRENT BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_OPENENDED_ANNUALLY_CARD = "OPENEND ANNUALLY WHEN BEG PAST BY CARD";
    public static final String FUTURE_WITH_DWNPAY_OPENEND_QUARTERLY_CARD = "OPENEND QUARTERLY WITH DOWN PAY WHEN BEG FUTURE BY CARD";
    public static final String FUTURE_WITH_DWNPAY_OPENEND_SEMIANNUALLY_CARD = "OPENEND SEMIANNUALLY WITH DOWN PAY WHEN BEG FUTURE BY CARD";
    public static final String FUTURE_WITHOUT_DWNPAY_OPENEND_SEMIANNUALLY_CARD = "OPENEND SEMIANNUALLY WHEN BEG FUTURE BY CARD";
    public static final String CURRENT_WITHOUT_DWNPAY_OPENEND_WEEKLY_CARD = "OPENEND WEEKLY WITHOUT DOWN PAY WHEN BEG CURRENT";
    public static final String FUTURE_WITHOUT_DWNPAY_OPENEND_QUARTERLY_CARD = "OPENEND QUARTERLY WITH DOWN PAY WHEN BEG FUTURE BY CARD";
    public static final String PAST_WITH_DWNPAY_OPENENDED_BIWEEKLY_CARD = "OPENEND BIWEEKLY WITH DWNPAY BEG PAST_CARD";
    public static final String PAST_WITH_DWNPAY_OPENEND_SEMIANNUALLY_CARD = "OPENEND SEMIANNUALLY WITH DOWN PAY WHEN BEG PAST BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_OPENEND_QUATERLY_CARD = "OPENEND QUATERLY WITHOUT DOWN PAY WHEN BEG PAST BY CARD";
    public static final String CURRENT_WITH_DWNPAY_OPENENDED_QUARTERLY_CARD = "OPENEND SUBS QUATERLY WITH DWNPAY BEG CURRENT BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_OPENENDED_MONTHLY_CARD = "OPENEND MONTHLY WITHOUT DWNPAY BEG PAST BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_OPENENDED_BIWEEKLY_CARD = "OPENEND BIWEEKLY WITHOUT DWNPAY BEG DATE PAST BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_OPENENDED_WEEKLY_CARD = "OPENEND WEEKLY WITHOUT DOWNPAY BEG DATE PAST BY CARD";
    public static final String CURRENT_WITHOUT_DWNPAY_OPENEND_BIWEEKLY_CARD = "OPENEND BIWEEKLY WITHOUT DOWN PAY WHEN BEG CURRENT";
    public static final String CURRENT_WITH_DWNPAY_OPENEND_ANNUALLY_CARD = "OPENEND ANNUALLY WITH DOWN PAY WHEN BEG CURRENT";
    public static final String CURRENT_WITH_DWNPAY_OPENEND_MONTHLY_CARD = "OPENEND MONTHLY WITH DOWN PAY WHEN BEG CURRENT";
    public static final String CURRENT_WITHOUT_DWNPAY_OPENENDED_QUARTERLY_CARD = "OPENEND SUBS QUATERLY WITHOUT DWNPAY BEG CURRENT BY CARD";
    public static final String CURRENT_WITHOUT_DWN_PAY_OPENENDED_SEMIANNUALLY_CARD = "OPENEND SEMIANNUALLY WITHOUT DWN PAY WHEN BEG CURRENT";
    /*Section name for AutoRenew To Open By Bank
     */


    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_BANK = "INSTALLMENT SEMI ANNUALLY WITH DWNPAY BEG FIRST DUE EXP FUTURE WITH AUTO-RENEW TO OPEN";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOOPEN_WEEKLY_BANK = "INSTALLMENT WEEKLY WITHOUT DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_WEEKLY_BANK = "INSTALLMENT WEEKLY WITH DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_BIWEEKLY_BANK = "INSTALLMENT BI WEEKLY  WITH DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOOPEN_BIWEEKLY_BANK = "INSTALLMENT BI WEEKLY  WITHOUT DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOOPEN_BIWEEKLY_BANK = "INSTALLMENT BI WEEKLY  WITHOUT DWNPAY BEG CURRENT WITH AUTO-RENEW TO OPEN";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_BANK = "INSTALLMENT SEMIANNUALLY WITHOUT DWNPAY BEG CURRENT WITH AUTO-RENEW TO OPEN";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOOPEN_WEEKLY_BANK = "INSTALLMENT WEEKLY  WITHOUT DWNPAY BEG CURRENT WITH AUTO-RENEW TO OPEN";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOOPEN_QUATERLY_BANK = "INSTALLMENT QUATERLY WITHOUT DWNPAY BEG FIRST DUE DATE CURRENT WITH AUTO-RENEW TO OPEN";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_BANK = "INSTALLMENT ANNUAL WITHOUT DWNPAY BEG CURRENT WITH AUTO-RENEW TO OPEN";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_QUARTERLY_BANK = "INSTALLMENT QUATERLY WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_QUARTERLY_BANK = "INSTALLMENT QUATERLY WITH DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_BANK = "INSTALLMENT SEMI ANNUAL WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_BANK = "INSTALLMENT SEMI ANNUAL WITH DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_BIWEEKLY_BANK = "INSTALLMENT BI WEEKLY  WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_BIWEEKLY_BANK = "INSTALLMENT BI WEEKLY WITH DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_WEEKLY_BANK = "INSTALLMENT WEEKLY  WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_WEEKLY_BANK = "INSTALLMENT WEEKLY WITH DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_BANK = "INSTALLMENT ANNUALLY  WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_BANK = "INSTALLMENT ANNUALLY WITH DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_MONTHLY_BANK = "INSTALLMENT MONTHLY WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN";
    public static final String CURRENT_WITH_DWNPAY_AUTORENEWTOOPEN_QUATERLY_BANK = "INSTALLMENT QUATERLY WITH DWNPAY BEG FIRST DUE DATE CURRENT WITH AUTO-RENEW TO OPEN";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_QUARTERLY_BANK = "INSTALLMENT QUARTERLY WITH DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN BY BANK";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_MONTHLY_BANK = "INSTALLMENT MONTHLY WITH DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN BY BANK";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOOPEN_QUARTERLY_BANK = "INSTALLMENT QUARTERLY WITHOUT DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN BY BANK";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_BANK = "INSTALLMENT ANNUALLY WITH DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN BY BANK";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_BANK = "INSTALLMENT SEMIANNUALLY WITHOUT DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN BY BANK";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_BANK = "INSTALLMENT ANNUALLY WITHOUT DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN BY BANK";
    /*Section name for Non Renewal Agreement By Bank
     */

    public static final String FUTURE_WITH_DWNPAY_NONRENEW_ANNUALLY_BANK = "INSTALLMENT ANNUALLY BEG FIRST DUE DATE FUTURE NON-RENEWAL AGREEMENT";
    public static final String PAST_WITHOUT_DWNPAY_NONRENEW_MONTHLY_BANK = "INSTALLMENT MONTHLY WITH NON RENEW BEG PAST EXP FUTURE BY BANK";
    public static final String FUTURE_WITH_DWNPAY_NONRENEW_BIWEEKLY_BANK = "INSTALLMENT BI-WEEKLY BEG FIRST DUE EXPIRATION DATE FUTURE NON-RENEWAL AGREEMENT";
    public static final String PAST_WITH_DWNPAY_NONRENEW_WEEKLY_BANK = "INSTALLMENT WEEKLY BEG FIRST DUE DATE PAST NON-RENEWAL AGREEMENT";
    public static final String FUTURE_WITHOUT_DWNPAY_NONRENEW_BIWEEKLY_BANK = "INSTALLMENT BI-WEEKLY WITHOUT BEG FUTURE";
    public static final String FUTURE_WITH_DWNPAY_NONRENEW_WEEKLY_BANK = "INSTALLMENT WEEKLY BEG FIRST DUE EXPIRE DATE FUTURE NON-RENEWAL AGREEMENT WITH DWNPAY";
    public static final String FUTURE_WITHOUT_DWNPAY_NONRENEW_MONTHLY_BANK = "INSTALLMENT MONTHLY WITHOUT DWNPAY BEG FUTURE";
    public static final String FUTURE_WITH_DWNPAY_NONRENEW_MONTHLY_BANK = "INSTALLMENT MONTHLY WITH DWNPAY BEG FUTURE";
    public static final String FUTURE_WITHOUT_DWNPAY_NONRENEW_QUARTERLY_BANK = "INSTALLMENT QUARTERLY WITHOUT DWNPAY BEG FUTURE NON RENEWAL";
    public static final String FUTURE_WITHOUT_DWNPAY_NONRENEW_SEMIANNUALLY_BANK = "INSTALLMENT SEMIANNUALLY WITHOUT DWNPAY BEG FUTURE";
    public static final String FUTURE_WITH_DWNPAY_NONRENEW_SEMIANNUALLY_BANK = "INSTALLMENT SEMIANNUALLY WITH DWNPAY BEG FUTURE NON RENEWAL";
    public static final String CURRENT_WITHOUT_DWNPAY_NONRENEW_SEMIANNUALLY_BANK = "INSTALLMENT SEMIANNUALLY WITHOUT DWNPAY BEG CURRENT NON RENEWAL";
    public static final String PAST_WITHOUT_DWNPAY_NONRENEW_SEMIANNUALLY_BANK = "INSTALLMENT SEMIANNUALLY WITH NON RENEW BEG PAST";
    public static final String FUTURE_WITHOUT_DWNPAY_NONRENEW_WEEKLY_BANK = "INSTALLMENT WEEKLY WITHOUT DWNPAY BEG FUTURE";
    public static final String CURRENT_WITH_DWNPAY_NONRENEW_WEEKLY_BANK = "INSTALLMENT WEEKLY WITH DWNPAY BEG CURRENT NON RENEWAL";
    public static final String CURRENT_WITHOUT_DWNPAY_NONRENEW_ANNUALLY_BANK = "NON-RENEWAL AGREEMENT WITHOUT DWNPAY BEG DATE CURRENT";
    public static final String FUTURE_WITHOUT_DWNPAY_NONRENEW_ANNUALLY_BANK = "INSTALLMENT ANNUALLY BEG DATE FUTURE NON-RENEWAL AGREEMENT";
    public static final String CURRENT_WITH_DWNPAY_NONRENEW_ANNUALLY_BANK = "NON-RENEWAL AGREEMENT WITH DWNPAY BEG DATE CURRENT";
    public static final String PAST_WITH_DWNPAY_NONRENEW_ANNUALLY_BANK = "NON RENEWAL AGREEMENT ANNUALLY WITH DWNPAY BEG PAST";
    public static final String PAST_WITHOUT_DWNPAY_NONRENEW_BIWEEKLY_BANK = "INSTALLMENT BI-WEEKLY BEG DUE DATE PAST NON-RENEWAL AGREEMENT";
    public static final String CURRENT_WITHOUT_DWNPAY_NONRENEW_QUARTERLY_BANK = "INSTALLMENT QUARTERLY WITHOUT DWNPAY BEG CURRENT WITH NONRENEWAL AGREEMENT";
    public static final String FUTURE_WITH_DWNPAY_NONRENEW_QUARTERLY_BANK = "NONRENEWAL AGREEMENT QUARTERLY WITH DWNPAY BEG FUTURE";
    public static final String PAST_WITHOUT_DWNPAY_NONRENEW_QUARTERLY_BANK = "INSTALLMENT QUARTERLY WITHOUT DWNPAY BEG PAST WITH NONRENEWAL AGREEMENT";
    public static final String CURRENT_WITHOUT_DWNPAY_NONRENEW_WEEKLY_BANK = "INSTALLMENT WEEKLY WITHOUT DWNPAY BEG CURRENT WITH NONRENEWAL AGREEMENT";
    public static final String PAST_WITHOUT_DWNPAY_NONRENEW_ANNUALLY_BANK = "NON RENEWAL AGREEMENT ANNUALLY WITHOUT DWNPAY BEG PAST";
    public static final String CURRENT_WITH_DWNPAY_NONRENEW_BIWEEKLY_BANK = "INSTALLMENT BI-WEEKLY BEG FIRST DUE EXPIRATION DATE CURRENT NON-RENEWAL AGREEMENT";
    /*Section name for AutoRenew To Term By Bank
     */

    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOTERM_MONTHLY_BANK = "INSTALLMENT MONTHLY WITHOUT DWNPAY BEG PAST AUTO RENEW TO TERM";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOTERM_SEMIANNUALLY_BANK = "INSTALLMENT SEMIANNUALLY WITHOUT DWNPAY BEG CURRENT WITH AUTO-RENEW TO TERM";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOTERM_SEMIANNUALLY_BANK = "INSTALLMENT SEMI-ANNUALLY BEG DATE PAST";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOTERM_BIWEEKLY_BANK = "INSTALLMENT BIWEEKLY WITHOUT DWNPAY BEG PAST AUTO-RENEW TO TERM";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOTERM_ANNUALLY_BANK = "INSTALLMENT ANNUAL WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO TERM BY BANK";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOTERM_MONTHLY_BANK = "INSTALLMENT MONTHLY WITHOUT DWNPAY BEG CURRENT WITH AUTO-RENEW TO TERM BY BANK";
    public static final String CURRENT_WTHOUT_DWNPAY_AUTORENEWTOOPEN_MONTHLY_BANK = "INSTALLMENT MONTHLY WITHOUT DWNPAY BEG CURRENT WITH AUTO-RENEW TO OPEN";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOTERM_QUATERLY_BANK = "INSTALLMENT QUATERLY WITH DWNPAY BEG FUTURE WITH AUTO-RENEW TO TERM BY BANK";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOTERM_MONTHLY_BANK = "INSTALLMENT MONTHLY WITH DWNPAY BEG FUTURE WITH AUTO-RENEW TO TERM BY BANK";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOTERM_QUARTERLY_BANK = "INSTALLMENT QUATERLY WITH DWNPAY BEG CURRENT WITHOUT AUTO-RENEW TO TERM BY BANK";

    /*Section name for installement AutoRenew To Open By Card
     */
    public static final String CUURENT_WITHOUT_DWNPAY_AUTORENEWTOOPEN_QUATERLY_CARD = "INSTALLMENT AUTO RENEW TO OPEN QUATERLY WITHOUT DWNPAY BEG CURRENT BY CARD";
    public static final String Future_WITHOUT_DWNPAY_AUTORENEWTOOPEN_MONTHLY_CARD = "INSTALLMENT MONTHLY WITHOUT DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN BY CREDIT CARD";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOOPEN_MONTHLY_CARD = "INSTALLMENT MONTHLY WITHOUT DWNPAY BEG CURRENT WITH AUTO-RENEW TO OPEN BY CREDIT CARD";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_CARD = "INSTALLMENT ANNUALLY WITH DWNPAY BEGANDEXP FUTURE CARD";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOOPEN_BIWEEKLY_CARD = "INSTALLMENT BIWEEKLY  WITHOUT DWNPAY BEG CURRENT WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOOPEN_WEEKLY_CARD = "INSTALLMENT WEEKLY  WITHOUT DWNPAY BEG CURRENT WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_CARD = "INSTALLMENT ANNUALLY WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_BIWEEKLY_CARD = "INSTALLMENT BIWEEKLY WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_MONTHLY_CARD = "INSTALLMENT MONTHLY WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_QUARTERLY_CARD = "INSTALLMENT QUARTERLY WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_QUARTERLY_CARD = "INSTALLMENT QUARTERLY WITH DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_BIWEEKLY_CARD = "INSTALLMENT BIWEEKLY WITH DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_CARD = "INSTALLMENT SEMI ANNUALLY WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_WEEKLY_CARD = "AUTO-RENEW TO OPEN WEEKLY SUB WITH DWNPAY BEG AND DUE DATE PAST";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_WEEKLY_CARD = "INSTALLMENT WEEKLY WITHOUT DWNPAY BEG PAST WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOOPEN_QUATERLY_CARD = "INSTALLMENT SEMIANNUALLY WITHOUT DWNPAY BEG FUTURE WITH NON RENEW";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOOPEN_BIWEEKLY_CARD = "INSTALLMENT BI WEEKLY  WITHOUT DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN CARD";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_CARD = "INSTALLMENT ANNUALLY BEG CURRENT AUTO-RENEW TO OPEN BY CREDIT CARD";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_ANNUAL_CARD = "INSTALLMENT ANNUALLY BEG PAST AUTO-RENEW TO OPEN BY CREDIT CARD";
    public static final String CURRENT_WITHOUT_DWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_CARD = "INSTALLMENT SEMIANNUALLY WITHOUT DWNPAY BEG CURRENT WITH AUTO RENEW TO OPEN";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_MONTHLY_CARD = "INSTALLMENT MONTHLY WITH DWNPAY BEG CURRENT FUTURE WITH AUTO-RENEW TO OPEN BY CREDIT CARD";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_CARD = "INSTALLMENT ANNUAL WITHOUT DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String CURRENT_WITH_DWNPAY_AUTORENEWTOOPEN_WEEKLY_CARD = "INSTALLMENT WEEKLY WITH DWNPAY BEG CURRENT WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String CURRENT_WITH_DWNPAY_AUTORENEWTOOPEN_MONTHLY_CARD = "INSTALLMENT MONTHLY WITH DWNPAY BEG CURRENT WITH AUTO-RENEW TO OPEN BY CREDIT CARD";
    public static final String CURRENT_WITH_DWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_CARD = "INSTALLMENT SEMIANNUALLY WITH DWNPAY BEG CURRENT WITH AUTO RENEW TO OPEN";
    public static final String CURRENT_WITH_DWNPAY_AUTORENEWTOOPEN_BIWEEKLY_CARD = "INSTALLMENT BIWEEKLY WITH DWNPAY BEG CURRENT WITH AUTO RENEW TO OPEN";
    public static final String CURRENT_WITH_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_CARD = "INSTALLMENT ANNUALLY WITH DWNPAY BEG CURRENT WITH AUTO RENEW TO OPEN";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_CARD = "INSTALLMENT WITH DWNPAY ANNUALLY BEG PAST AUTO-RENEW TO OPEN BY CREDIT CARD";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOOPEN_MONTHLY_CARD = "INSTALLMENT MONTHLY WITHOUT DWNPAY BEG FUTURE WITH AUTO RENEW TO OPEN";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_BIWEEKLY_CARD = "INSTALLMENT BI WEEKLY  WITH DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN CARD";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_WEEKLY_CARD_EXP_DATE_PAST = "INSTALLMENT WEEKLY WITHOUT DWNPAY BEG AND DUE PAST WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_WEEKLY_CARD = "INSTALLMENT WEEKLY WITH DWNPAY BEG  FUTURE WITH AUTO-RENEW TO OPEN BY CREDIT CARD";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_CARD_EXP_DATE_PAST = "INSTALLMENT WEEKLY WITHOUT DWNPAY BEG AND DUE PAST WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_MONTHLY_CARD_EXP_DATE_PAST = "INSTALLMENT MONTHLY WITH DWNPAY BEG AND EXP PAST WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOOPEN_WEEKLY_CARD = "INSTALLMENT WEEKLY WITHOUT DWNPAY BEG  FUTURE WITH AUTO-RENEW TO OPEN BY CREDIT CARD";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOOPEN_ANNUALLY_CARD_EXP_DATE_FUTURE = "INSTALLMENT WITH DWNPAY ANNUALLY BEG AND EXP PAST AUTO-RENEW TO OPEN BY CREDIT CARD";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_QUARTERLY_CARD = "INSTALLMENT QUARTERLY WITH DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_CARD = "INSTALLMENT SEMIANNUALLY WITHOUT DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_CARD = "INSTALLMENT SEMIANNUALLY WITH DWNPAY BEG FUTURE WITH AUTO-RENEW TO OPEN BY CARD";
    public static final String CURRENT_WITH_DWNPAY_AUTORENEWTOOPEN_QUARTERLY_CARD = "INSTALLMENT QUARTERLY WITH DWNPAY BEG CURRENT WITH AUTO-RENEW TO OPEN BY CARD";
    /*Section name for installement AutoRenew To Term By Card
     */
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOOPEN_SEMIANNUAL_CARD = "INSTALLMENT SEMI ANNUAL WITH DWNPAY BEG FIRST DUE EXP FUTURE WITH AUTO-RENEW TO TERM BY CARD";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOTERM_MONTHLY_CARD = "INSTALLMENT MONTHLY WITHOUT DWNPAY BEG PAST EXP FUTURE WITH AUTO-RENEW TO TERM";
    public static final String FUTURE_WITHOUT_DWNPAY_AUTORENEWTOTERM_WEEKLY_CARD = "INSTALLMENT ANNUAL WITHOUT DWNPAY BEG FUTURE WITH AUTO-RENEW TO TERM BY CARD";
    public static final String FUTURE_WITH_DWNPAY_AUTORENEWTOTERM_WEEKLY_CARD = "INSTALLMENT ANNUAL WITH DWNPAY BEG FUTURE WITH AUTO-RENEW TO TERM BY CARD";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOTERM_BIWEEKLY_CARD = "AUTO-RENEW TO TERM BIWEEKLY WITH DWNPAY BEG PAST";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOTERM_SEMIANNUALLY_CARD = "AUTO-RENEW TO TERM BY CARD SEMIANNUALLY WITHOUT DWNPAY BEG PAST";
    public static final String PAST_WITHOUT_DWNPAY_AUTORENEWTOTERM_MONTHLY_CARD = "INSTALLMENT MONTHLY WITH DWNPAY BEG FIRST PAST WITH AUTO-RENEW TO TERM BY CARD";
    public static final String PAST_WITH_DWNPAY_AUTORENEWTOTERM_WEEKLY_CARD = "AUTO-RENEW TO TERM WEEKLY WITH DWNPAY BEG PAST";
    /*Section name for installement Non renewal agreement By Card
     */
    public static final String FUTURE_WITH_DWNPAY_NONRENEW_BIWEEKLY_CARD = "INSTALLMENT BIWEEKLY BEG FIRST DUE DATE PAST NON RENEW BY CARD";
    public static final String FUTURE_WITHOUT_DWNPAY_NONRENEW_BIWEEKLY_CARD = "INSTALLMENT SEMI-ANNUALLY BEG FIRST DUE DATE PAST AND EXP DATE FUTURE NON RENEW BY CARD";
    public static final String CURRENT_WITHOUT_DWNPAY_NONRENEW_BIWEEKLY_CARD = "INSTALLMENT BIWEEKLY WITHOUT DWNPAY BEG CURRENT NON RENEWAL";
    public static final String CURRENT_WITHOUT_DWNPAY_NONRENEW_QUARTERLY_CARD = "INSTALLMENT QUARTERLY WITHOUT DWNPAY BEG CURRENT NON RENEWAL";
    public static final String FUTURE_WITHOUT_DWNPAY_NONRENEW_QUATERLY_CARD = "INSTALLMENT SEMIANNUALLY WITHOUT DWNPAY BEG PAST WITH NON RENEW";
    public static final String CURRENT_WITHOUT_DWNPAY_NONRENEW_WEEKLY_CARD = "INSTALLMENT WEEKLY WITHOUT DWNPAY BEG CURRENT NON RENEWAL";
    public static final String CURRENT_WITHOUT_DWNPAY_NONRENEW_ANNUALLY_CARD = "INSTALLMENT WEEKLY WITHOUT DWNPAY BEG CURRENT NON RENEWAL";
    public static final String CURRENT_WITHOUT_DWNPAY_NONRENEW_SEMIANNUAL_CARD = "NON RENEWAL AGREEMENT SEMIANNUALLY WITHOUT DWNPAY BEG CURRENT";
    public static final String CURRENT_WITH_DWNPAY_NONRENEW_WEEKLY_CARD = "INSTALLMENT WEEKLY BEG FIRST DUE DATE CURRENT NON RENEW BY CARD";
    public static final String CURRENT_WITH_DWNPAY_NONRENEW_QUARTERLY_CARD = "INSTALLMENT QUARTERLY BEG FIRST DUE DATE CURRENT NON RENEW BY CARD";
    public static final String FUTURE_WITH_DWNPAY_NONRENEW_WEEKLY_CARD = "INSTALLMENT WEEKLY BEG FIRST DUE DATE FUTURE NON RENEW BY CARD";
    public static final String FUTURE_WITH_DWNPAY_NONRENEW_ANNUALLY_CARD = "INSTALLMENT ANNUALLY BEG FIRST DUE DATE FUTURE NON RENEW BY CARD";
    public static final String PAST_WITH_DWNPAY_NONRENEW_ANNUALLY_CARD = "INSTALLMENT WEEKLY BEG FIRST DUE DATE PAST NON RENEW BY CARD";
    public static final String PAST_WITH_DWNPAY_NONRENEW_QUARTERLY_CARD = "INSTALLMENT QUARTERLY BEG FIRST DUE DATE PAST NON RENEW BY CARD";
    /*Section name for multiple Open-ended subscription with Bank*/
    public static final String MULTIPLE_SUBS_CURRENT_WITH_DWNPAY_OPEMENDED_WEEKLY_BANK = "OPEN ENDED WEEKLY MULTIPLE CURRENT WITH DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_CURRENT_WITHOUT_DWNPAY_OPEMENDED_BIWEEKLY_BANK = "OPEN ENDED BIWEEKLY MULTIPLE CURRENT WITHOUT DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_CURRENT_WITHOUT_DWNPAY_OPEMENDED_WEEKLY_BANK = "OPEN ENDED WEEKLY MULTIPLE CURRENT WITHOUT DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_PAST_WITHOUT_DWNPAY_OPEMENDED_QUARTERLY_BANK = "OPEN ENDED QUARTERLY MULTIPLE PAST WITHOUT DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_FUTURE_WITHOUT_DWNPAY_OPEMENDED_SEMIANNUALLY_BANK = "OPEN ENDED SEMIANNUALLY MULTIPLE FUTURE WITHOUT DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_PAST_WITHOUT_DWNPAY_OPEMENDED_MONTHLY_BANK = "OPEN ENDED MONTHLY MULTIPLE PAST WITHOUT DWN PAY BY BANK";

    public static final String MULTIPLE_SUBS_PAST_WITH_DWNPAY_OPEMENDED_ANNUALLY_BANK = "NON RENEW WEEKLY MULTIPLE PAST WITH DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_CURRENT_WITH_OPEN_ENDED_MONTHLY_BANK = "OPEN ENDED MONTHLY MULTIPLE CURRENT WITH DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_CURRENT_WITH_OPEN_ENDED_SEMIANNUALLY_BANK = "OPEN ENDED SEMIANNUALLY MULTIPLE CURRENT WITH DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_CURRENT_WITH_OPEN_ENDED_BI_WEEKLY_BANK = "OPEN ENDED BI-WEEKLY MULTIPLE CURRENT WITH DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_CURRENT_WITH_NON_RENEW_BI_ANNUALLY_BANK = "NON RENEW ANNUALLY MULTIPLE CURRENT WITH DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_CURRENT_WITH_NON_RENEW_QUARTERLY_BANK = "NON RENEW QUARTERLY MULTIPLE CURRENT WITH DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_CURRENT_WITH_NON_RENEW_WEEKLYY_BANK = "NON RENEW WEEKLY MULTIPLE CURRENT WITH DWN PAY BY BANK";
    public static final String MULTIPLE_SUBS_PAST_WITH_DWNPAY_NONRENEW_MONTHLY_BANK = "MULTIPLE SUBS SECOND SUBS NON RENEW MONTHLY WITH DWN WHEN BEG PAST";
    public static final String MULTIPLE_SUBS_PAST_WITH_DWNPAY_NONRENEW_QUARTERLY_BANK = "MULTIPLE SUBS SECOND SUBS NON RENEW QUARTERLY WHEN BEG PAST";
    public static final String MULTIPLE_SUBS_PAST_WITH_DWNPAY_NONRENEW_SEMIANNUALLY_BANK = "MULTIPLE SUBS SECOND SUBS NON RENEW SEMI-ANNUALLY WHEN BEG PAST";
    public static final String MULTIPLE_PAST_WITH_DWNPAY_NONRENEW_MONTHLY_BANK = "MULTIPLE SUBS SECOND SUBS NON RENEW MONTHLY WITH DWN WHEN BEG PAST EXP DATE CURRENT";
    public static final String MULTIPLE_SUBS_PAST_WITH_DWNPAY_OPENENDED_ANNUALLY_BANK = "OPENEND ANNUALLY WHEN BEG PAST";

    /*Section name for multiple Open-ended subscription with Card*/
    public static final String MULTIPLE_SUBS_PAST_WITHOUT_DWNPAY_OPENENDED_MONTHLY_CARD = "OPEN ENDED MONTHLY MULTIPLE PAST_WITHOUT DWN PAY BY CARD";
    public static final String MULTIPLE_SUBS_CURRENT_WITHOUT_DWNPAY_OPENENDED_QUARTERLY_CARD = "OPEN ENDED QUARTERLY MULTIPLE PAST_WITHOUT DWN PAY BY CARD";
    public static final String MULTIPLE_SUBS_CURRENT_WITHOUT_DWNPAY_OPENENDED_SEMIANNUALLY_CARD = "OPEN ENDED SEMIANNUALLY MULTIPLE PAST_WITHOUT DWN PAY BY CARD";
    public static final String MULTIPLE_SUBS_CURRENT_WITHOUT_DWNPAY_OPENENDED_BIWEEKLY_CARD = "OPEN ENDED BIWEEKLY MULTIPLE PAST_WITHOUT DWN PAY BY CARD";
    public static final String MULTIPLE_SUBS_CURRENT_WITHOUT_DWNPAY_OPENENDED_ANNUALLY_CARD = "OPEN ENDED ANNUALLY MULTIPLE CURRENT WITHOUT DWN PAY BY CARD";
    public static final String MULTIPLE_SUBS_CURRENT_WITHOUT_DWNPAY_OPENENDED_BIWEEKLY_AMEX_CARD = "OPEN ENDED BIWEEKLY MULTIPLE CURRENT WITHOUT DWN BY AMEX CARD";
    public static final String MULTIPLE_SUBS_CURRENT_WITHOUT_DWNPAY_OPENENDED_MONTHLY_CARD = "OPEN ENDED MONTHLY MULTIPLE CURRENT WITHOUT DWN PAY BY CARD";

    public static final String MULTIPLE_SUBS_PAST_WITHOUT_DWNPAY_NON_RENEW_WEEKLY_CARD = "NON-RENEW MONTHLY MULTIPLE PAST WITHOUT DWN PAY BY CARD";
    public static final String MULTIPLE_SUBS_PAST_WITHOUT_DWNPAY_NON_RENEW_MONTHLY_CARD = "NON-RENEW WEEKLY MULTIPLE CURRENT WITHOUT DWN PAY BY CARD";

    public static final String MULTIPLE_SUBS_PAST_WITHOUT_DWNPAY_NON_RENEW_SEMIANNUALLY_CARD="NON-RENEW SEMIANNUALLY MULTIPLE PAST WITHOUT DWN PAY BY CARD";



    /*Section name for multiple location subscription  Bank*/
    public static final String PAST_MULTIPLE_LOCATION_NONRENEW_YEARLY_BANK = "PAST_MULTIPLE_LOCATION_NONRENEW_YEARLY_BANK";
    public static final String PAST_MULTIPLE_LOCATION_NONRENEW_MONTHLY_BANK = "PAST_MULTIPLE_LOCATION_NONRENEW_MONTHLY_BANK";
    public static final String PAST_MULTIPLE_LOCATION_OPENENDED_MONTHLY_BANK = "PAST_MULTIPLE_LOCATION_OPENENDED_MONTHLY_BANK";
    public static final String CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_QUARTERLY_BANK = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_QUARTERLY_BANK";
    public static final String CURRENT_MULTIPLE_LOCATION_AUTORENEWTOTERM_QUARTERLY_BANK = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOTERM_QUARTERLY_BANK";
    /*Section name for multiple location subscription Card*/
    public static final String CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_WEEKLY_CARD = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_WEEKLY_CARD";
    public static final String CURRENT_MULTIPLE_LOCATION_AUTORENEWTOTERM_WEEKLY_CARD = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOTERM_WEEKLY_CARD";
    public static final String CURRENT_MULTIPLE_LOCATION_AUTORENEWTOTERM_MONTHLY_WITH_DWN_PAY_CARD = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOTERM_MONTHLY_WITH_DWN_PAY_CARD";
    public static final String PAST_MULTIPLE_LOCATION_OPENENDED_MONTHLY_WITH_DWN_PAY_CARD = "PAST_MULTIPLE_LOCATION_OPENENDED_MONTHLY_WITH_DWN_PAY_CARD";
    public static final String CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_ANNUALLY_CARD = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_ANNUALLY_CARD";
    public static final String CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_BIWEEKLY_CARD = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_BIWEEKLY_CARD";
    public static final String CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_QUARTERLY_CARD = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_QUARTERLY_CARD";
    public static final String CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_QUARTERLY_CARD_DWN_PAY = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_QUARTERLY_CARD_DWN_PAY";
    public static final String CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_SEMIANNUALLY_CARD = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_SEMIANNUALLY_CARD";
    public static final String CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_MONTHLY_CARD = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_MONTHLY_CARD";
    public static final String CURRENT_MULTIPLE_LOCATION_WITHDWNPAY_AUTORENEWTOOPEN_MONTHLY_CARD = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_MONTHLY_WITHDWNPAY_CARD";
    public static final String CURRENT_MULTIPLE_LOCATION_WITHDWNPAY_AUTORENEWTOOPEN_SEMIANNUALLY_CARD = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_SEMIANNUALLY_WITHDWNPAY_CARD";
    public static final String CURRENT_MULTIPLE_LOCATION_WITHDWNPAY_AUTORENEWTOOPEN_BIWEEKLY_CARD = "CURRENT_MULTIPLE_LOCATION_AUTORENEWTOOPEN_BIWEEKLY_WITHDWNPAY_CARD";
    public static final String CURRENT_MULTIPLE_LOCATION_FUTURE_AUTORENEWTOOPEN_ANNUALLY_ANNUAL_CARD_DWN_PAY = "CURRENT_MULTIPLE_LOCATION_FUTURE_AUTORENEWTOOPEN_ANNUALLY_ANNUAL_CARD_DWN_PAY";
    /*Section name for multiple member subscription */
    public static final String CURRENT_MULTIPLE_MEMBER_AUTORENEWTOTERM_MONTHLY_BANK = "CURRENT MULTIPLE MEMBER AUTORENEWTOTERM MONTHLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_AUTORENEWTOTERM_WEEKLY_BANK = "CURRENT MULTIPLE MEMBER AUTORENEWTOTERM WEEKLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_AUTORENEWTOTERM_BIWEEKLY_BANK = "CURRENT MULTIPLE MEMBER AUTORENEWTOTERM BIWEEKLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_AUTORENEWTOTERM_QUARTERLY_BANK = "CURRENT MULTIPLE MEMBER AUTORENEWTOTERM QUARTERLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_AUTORENEWTOTERM_ANNUALLY_BANK = "CURRENT MULTIPLE MEMBER AUTORENEWTOTERM ANNUALLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_MONTHLY_BANK = "CURRENT MULTIPLE MEMBER OPENENDED MONTHLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_MONTHLY_WTH_DWN_PAY_BANK = "CURRENT MULTIPLE MEMBER OPENENDED MONTHLY WITH DWN PAY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_WEEKLY_BANK = "CURRENT MULTIPLE MEMBER OPENENDED WEEKLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_QUARTERLY_BANK = "CURRENT MULTIPLE MEMBER OPENENDED QUARTERLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_ANNUALLY_BANK = "CURRENT MULTIPLE MEMBER OPENENDED BI-WEEKLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_BIWEEKLY_BANK = "CURRENT MULTIPLE MEMBER OPENENDED BI-WEEKLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_SEMIANNUALLY_BANK = "CURRENT MULTIPLE MEMBER OPENENDED SEMI-ANNUALLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_AUTORENEWTOOPEN_WEEKLY_BANK = "CURRENT MULTIPLE MEMBER AUTORENEWTOPEN WEEKLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_AUTORENEWTOOPEN_BIWEEKLY_BANK = "CURRENT MULTIPLE MEMBER AUTORENEWTOPEN BIWEEKLY BANK";

    public static final String CURRENT_MULTIPLE_MEMBER_AUTORENEWTOOPEN_MONTHLY_BANK = "CURRENT MULTIPLE MEMBER AUTORENEWTOPEN MONTHLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_AUTORENEWTOOPEN_ANNUALLY_BANK = "CURRENT MULTIPLE MEMBER AUTORENEWTOPEN ANNUALLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_AUTORENEWTOOPEN_QUARTERLY_BANK = "CURRENT MULTIPLE MEMBER AUTORENEWTOPEN QUARTERLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_NONRENEWABLE_ANNUALLY_BANK = "CURRENT MULTIPLE MEMBER NONRENEWABLE ANNUALLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_NONRENEWABLE_WEEKLY_BANK = "CURRENT MULTIPLE MEMBER NONRENEWABLE WEEKLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_NONRENEWABLE_BIWEEKLY_BANK = "CURRENT MULTIPLE MEMBER NONRENEWABLE BIWEEKLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_NONRENEWABLE_MONTHLY_BANK = "CURRENT MULTIPLE MEMBER NONRENEWABLE MONTHLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_NONRENEWABLE_QUARTERLY_BANK = "CURRENT MULTIPLE MEMBER NONRENEWABLE QUARTERLY BANK";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_WEEKLY_CARD = "CURRENT MULTIPLE MEMBER OPENENDED WEEKLY CARD";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_MONTHLY_CARD = "CURRENT MULTIPLE MEMBER OPENENDED MONTHLY CARD";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_QUARTERLY_CARD = "CURRENT MULTIPLE MEMBER OPENENDED QUARTERLY CARD";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_ANNUALLY_CARD = "CURRENT MULTIPLE MEMBER OPENENDED ANNUALLY CARD";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_BIWEEKLY_CARD = "CURRENT MULTIPLE MEMBER OPENENDED BIWEEKLY CARD";
    public static final String CURRENT_MULTIPLE_MEMBER_OPENENDED_SEMIANNUALLY_CARD = "CURRENT MULTIPLE MEMBER OPENENDED SEMIANNUALLY CARD";


    /*Section name for field validation */
    public static final String CURRENT_WITHOUT_PAYMENT_AMOUNT_OPENENDED_MONTHLY = "CURRENT_WITHOUT_PAYMENT_AMOUNT_OPENENDED_MONTHLY";
    /*Negative Scenarios*/
    public static final String VERIFY_PAYMENT_METHOD_CHANGES_TO_TRANSFERRRED = "PAYMENT METHOD CHANGES TO TRANSFERRRED";
    public static final String VERIFY_PAYMENT_METHOD_STATUS_CHANGES_TO_PAYER_REVOKED = "PAYMENT METHOD STATUS CHANGES TO PAYER REVOKED";
    public static final String CREATE_SUBSCRIPTION_AFTER_PAYMENT_METHOD_STATUS_CHANGES_TO_PAYER_REVOKED = "CREATE SUBSCRIPTION AFTER PAYMENT METHOD STATUS CHANGES TO PAYER REVOKED";
    public static final String CURRENT_MULTIPLE_MEMBER_INSTALLMENT_MONTHLY_CARD_PAYOR_REVOKED = "CURRENT MULTIPLE MEMBER OPENENDED ANNUALLY CARD PAYOR REVOKED";
    public static final String CURRENT_MULTIPLELOCATION_NONRENEW_WEEKLY_BANK_PAYOR_REVOKED = "CURRENT MULTIPLE LOCATION NON RENEW WEEKLY BANK PAYOR REVOKED";
    public static final String CURRENT_MULTIPLESUBSCRIPTION_NONENEW_WEEKLY_CARD_PAYOR_REVOKED = "CURRENT MULTIPLE SUBSCRIPTION NON RENEW WEEKLY BANK PAYOR REVOKED";
    public static final String CURRENT_TRYING_TO_ADD_SUBS_AFTER_PAYMENT_METHOD_PAYER_REVOKED_AMEX = "CURRENT TRYING TO ADD SUBS AFTER PAYMENT METHOD PAYER REVOKED AMEX";
    public static final String CURRENT_MULTIPLE_SUBSCRIPTION_NON_RENEW_WEEKLY_TRANSFERRED_CARD = "CURRENT MULTIPLE SUBSCRIPTION NON RENEW WEEKLY TRANSFERRED CARD";
    public static final String CURRENT_MULTIPLELOCATION_OPENENDED_WEEKLY_SUBMITTED_FAILED = "CURRENT MULTIPLE LOCATION OPENENDED WEEKLY BANK SUBMITTED FAILED";
    public static final String CURRENT_MULTIPLELOCATION_OPENENDED_WEEKLY_BANK_PAYOR_REVOKED_ANOTHER_SUBS = "CURRENT MULTIPLE LOCATION OPEN-ENDED WEEKLY BANK PAYOR REVOKED ANOTHER SUBS";
    public static final String CURRENT_MULTIMEMBER_SUBMITTED_FAILED_DUE_TO_INCORRECT_PROCESSOR_LINKED = "CURRENT MULTIMEMBER SUBMITTED FAILED INCORRECT PROCESSOR LINKED";
    public static final String PAST_MULTIPLESUBSCRIPTION_NONRENEW_WEEKLY_CARD_PAYOR_REVOKED = "PAST MULTIPLE SUBSCRIPTION NON RENEW WEEKLY BANK PAYOR REVOKED";
    public static final String CURRENT_MULTIPLESUBSCRIPTION_NONRENEW_MONTHLY_CARD_PAYOR_REVOKED = "CURRENT MULTIPLE SUBSCRIPTION NON RENEW MONTHLY BANK PAYOR REVOKED";
    public static final String PAST_MULTIPLESUBSCRIPTION_NONRENEW_MONTHLY_CARD_INVALID_PROCESSOR = "PAST MULTIPLE SUBSCRIPTION NON RENEW MONTHLY BANK INVALID PROCESSOR";
    public static final String CURRENT_MULTIPLE_MEMBER_INSTALLMENT_WEEKLY_PAYMENT_METHOD_CHANGES_TO_TRANSFERRED = "CURRENT MULTIPLE MEMBER NON RENEW WEEKLY TRANSFERRED CARD";
    public static final String PAST_MULTIPLE_LOCATION_OPEN_ENDED_WEEKLY_BANK_PAYOR_REVOKED = "PAST MULTIPLE LOCATION OPEN ENDED WEEKLY BANK PAYOR REVOKED";
    public static final String CURRENT_MULTIPLE_MEMBER_INSTALLMENT_WEEKLY_CARD_PAYOR_REVOKED = "PAST MULTIPLE MEMBER NON RENEW WEEKLY CARD PAYOR REVOKED";
    public static final String CURRENT_MULTIPLESUBSCRIPTION_NONRENEW_WEEKLY_CARD_INVALID_PROCESSOR = "CURRENT MULTIPLE SUBSCRIPTION NON RENEW WEEKLY BANK INVALID PROCESSOR";
    public static final String CURRENT_MULTI_MEMBER_NONRENEW_WEEKLY_CARD_INVALID_PROCESSOR = "CURRENT MULTIPLE MEMBER NON RENEW WEEKLY CARD INVALID PROCESSOR";
    public static final String CURRENT_MULTIPLELOCATION_NONRENEW_WEEKLY_BANK_TRANSFERRED = "CURRENT MULTIPLE LOCATION NON RENEW WEEKLY BANK TRANSFERRED";


    /*Update member */
    public static final String UPDATE_MEMBER_PROFILE_DETAILS = "UPDATE MEMBER PROFILE";
    /*
     AccountDetail     */
    public static final String ACCOUNT_DETAIL_PAST_WITHOUT_DWNPAY_AUTORENEWTOOPEN_MONTHLY_BANK = "ACCOUNT DETAIL PAST WITHOUT DWNPAY AUTORENEWTOOPEN MONTHLY BANK";
    /*Freeze Subscription*/
    public static final String FREEZE_CURRENT_OPENENDED_WEEKLY_WITHOUT_DWNPAY_BANK = "FREEZE OPENEND WEEKLY WITHOUT DWNPAY BEG CURRENT";
    public static final String FREEZE_CURRENT_OPENENDED_BIWEEKLY_WITHOUT_DWNPAY_CARD = "FREEZE OPENEND BI-WEEKLY WITHOUT DWNPAY BEG CURRENT WITH CARD";

    /* MigratedData */
    public static final String MIGRATED_DATA = "MIGRATED_DATA";
    public static final String CLUB_ADDRESS = "clubAddress";
    public static final String CLUB_CITY = "clubCity";
    public static final String CLUB_ZIP = "clubZip";
    public static final String CLUB_PHONE = "clubPhone";
    //Migrated Data
    public static final String MIGRATED_SECTION = "MIGRATED_DATA";
}
